[package]
name = "tz-ingress"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
build = "build.rs"

[features]
default = ["tcp", "udp", "http"]
tcp = []
udp = []
http = ["dep:hyper", "dep:hyper-util", "dep:http-body-util", "dep:http"]

[dependencies]
portable-atomic.workspace = true
arc-swap.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures-util.workspace = true
inventory.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
dashmap.workspace = true
libc.workspace = true
socket2.workspace = true
tz-carrier.workspace = true
tz-guard.workspace = true
tz-net.workspace = true
tz-proto.workspace = true
uuid.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
tokio-rustls.workspace = true
rcgen.workspace = true
hyper = { workspace = true, optional = true }
hyper-util = { workspace = true, optional = true }
http-body-util = { workspace = true, optional = true }
http = { workspace = true, optional = true }

[lints]
workspace = true
