use std::{env, fs, path::Path};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let carriers_dir = Path::new(&manifest_dir).join("src/carriers");
    let mut modules = Vec::new();
    if let Ok(entries) = fs::read_dir(&carriers_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "rs") {
                if let Some(stem) = path.file_stem().and_then(|value| value.to_str()) {
                    modules.push(stem.to_string());
                }
            }
        }
    }
    modules.sort();
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let generated = Path::new(&out_dir).join("carriers.inc.rs");
    let mut source = String::from("// generated by build.rs\n");
    for module in &modules {
        let module_path = carriers_dir.join(format!("{module}.rs"));
        source.push_str(&format!(
            "#[path = {:?}]\nmod {module};\n",
            module_path.display()
        ));
    }
    fs::write(generated, source).expect("write carriers.inc.rs");
    println!("cargo:rerun-if-changed=src/carriers");
}
